"""
    fit([rng], problem, algorithm, X, y, [w_star])

Fit an `algorithm` to data `X, y` generated by `problem`, with randomness source `rng`.
"""
StatsAPI.fit

## ERM

function StatsAPI.fit(problem::Logistic, ::Union{ERM, NoResampling}, X::AbstractMatrix, y::AbstractVector)
    (; λ) = problem
    model = MLJLinearModels.LogisticRegression(
        λ; fit_intercept=false, scale_penalty_with_samples=false
    )
    w = MLJLinearModels.fit(model, X, y)
    return w
end

function StatsAPI.fit(problem::Ridge, ::ERM, X::AbstractMatrix, y::AbstractVector)
    (; λ) = problem
    model = MLJLinearModels.RidgeRegression(
        λ; fit_intercept=false, scale_penalty_with_samples=false
    )
    w = MLJLinearModels.fit(model, X, y)
    return w
end


function StatsAPI.fit(problem::Union{Lasso, LassoWithLassoTeacher}, ::ERM, X::AbstractMatrix, y::AbstractVector)
    (; λ) = problem
    model = MLJLinearModels.LassoRegression(
        λ; fit_intercept=false, scale_penalty_with_samples=false
    )
    w = MLJLinearModels.fit(model, X, y)
    return w
end

## Fallbacks

function StatsAPI.fit(
    ::AbstractRNG, problem::Problem, algo::Algorithm, X::AbstractMatrix, y::AbstractVector
)
    return fit(problem, algo, X, y)
end

function StatsAPI.fit(
    rng::AbstractRNG,
    problem::Problem,
    algo::Algorithm,
    X::AbstractMatrix,
    y::AbstractVector,
    w_star::AbstractVector,
)
    return fit(rng, problem, algo, X, y)
end

## Resampling

function StatsAPI.fit(
    rng::AbstractRNG,
    problem::Problem,
    ::PairBootstrap,
    X::AbstractMatrix,
    y::AbstractVector,
)
    n = length(y)
    ind = sample(rng, 1:n, n; replace=true)
    return @views fit(problem, ERM(), X[ind, :], y[ind])
end

function StatsAPI.fit(
    rng::AbstractRNG,
    problem::Problem,
    algo::Subsampling,
    X::AbstractMatrix,
    y::AbstractVector,
)
    n = length(y)
    ind = rand(rng, n) .< algo.r
    return @views fit(problem, ERM(), X[ind, :], y[ind])
end

function StatsAPI.fit(
    rng::AbstractRNG,
    problem::Problem,
    ::FullResampling,
    X::AbstractMatrix,
    y::AbstractVector,
    w_star::AbstractVector,
)
    n = length(y)
    teacher_dim = ceil(Int, problem.α * n)
    new_X = sample_data(rng, problem; n = n, teacher_dim = teacher_dim)
    new_y = sample_labels(rng, problem, new_X, w_star)
    return fit(problem, ERM(), new_X, new_y)
end

"""

for full resampling, we need to sample new labels and new data and for this 
we need to provide w_star
"""
function StatsAPI.fit(
    rng::AbstractRNG,
    problem::Union{RidgeOverparametrized, Ridge},
    ::FullResampling,
    X::AbstractMatrix,
    y::AbstractVector,
    w_star::AbstractVector,
    F::AbstractMatrix
)
    n = length(y)
    teacher_dim = ceil(Int, problem.α * n)
    new_X = sample_data(rng, problem; n = n, teacher_dim = teacher_dim)
    new_y = sample_labels(rng, problem, new_X, w_star)
    new_V = (problem.κ1 * new_X * F' + problem.κstar * randn(rng, size(new_X, 1), size(F, 2))) / sqrt(size(F, 2))
    return fit(problem, ERM(), new_V, new_y)
end

function StatsAPI.fit(
    rng::AbstractRNG,
    problem::Problem,
    ::LabelResampling,
    X::AbstractMatrix,
    y::AbstractVector,
    w_star::AbstractVector,
)
    new_y = sample_labels(rng, problem, X, w_star)
    return fit(problem, ERM(), X, new_y)
end
